export const NewArrival_DataArr = [
    {
        id: "42",
        image: "/NewArrival1.webp",
        hoverImage: "/NewArrival1.webp",
        description: "3 Pcs Attar Set Taabish, Safira And Safwan 5.5 ML Each",
        review: "",
        price: "₹799",
        deletePrice: "₹1,797",
        discount: "Save 56%",
    },
    {
        id: "43",
        image: "/NewArrival2.webp",
        hoverImage: "/NewArrival2.webp",
        description: "3 Pcs Attar Set Lavish Musk, Taabish And Safira 5.5 ML Each",
        review: "",
        price: "₹799",
        deletePrice: "1,797",
        discount: "Save 56%",
    },
    {
        id: "44",
        image: "/NewArrival3.webp",
        hoverImage: "/NewArrival3.webp",
        description: "2 Pcs Attar Set Shanaya And Shanaya Oudh 5.5 Ml Each",
        review: "",
        price: "₹699",
        deletePrice: "₹1,198",
        discount: "Save 42%",
    },
    {
        id: "45",
        image: "/NewArrival4.webp",
        hoverImage: "/NewArrival4.webp",
        description: "2 Pcs Attar Set Shanaya And Lazina 5.5 Ml Each",
        review: "",
        price: "₹699",
        deletePrice: "₹1,198",
        discount: "Save 42%",
    },
    {
        id: "46",
        image: "/NewArrival5.webp",
        hoverImage: "/NewArrival5.webp",
        description: "3 Pcs Attar Set Safira, Lavish Musk And Shanaya 5.5 ML Each",
        review: "",
        price: "₹799",
        deletePrice: "₹1,797",
        discount: "Save 56%",
    },
    {
        id: "47",
        image: "/NewArrival6.webp",
        hoverImage: "/NewArrival6.web",
        description: "3 Pcs Attar Set Safira, Safwan And Shanaya 5.5 ML Each",
        review: "",
        price: "₹799",
        deletePrice: "₹1,797",
        discount: "Save 56%",
    },
    {
        id: "48",
        image: "/NewArrival7.webp",
        hoverImage: "/NewArrival7.webp",
        description: "3 Pcs Perfume Set Shanaya, Shanaya Gold And The Story Perfume Spray 50 Ml Each",
        review: "",
        price: "₹2,199",
        deletePrice: "3,597",
        discount: "Save 39%",
    },
    {
        id: "49",
        image: "/NewArrival8.webp",
        hoverImage: "/NewArrival8.webp",
        description: "3 Pcs Perfume Set The Story, White Oudh And Oudh Al Hashmi Perfume Spray 50 Ml Each",
        review: "",
        price: "₹2,199",
        deletePrice: "₹3,597",
        discount: "Save 39%",
    },
    {
        id: "50",
        image: "/NewArrival9.webp",
        hoverImage: "/NewArrival9.webp",
        description: "3 Pcs Perfume Set Shanaya, White Oudh And The Story Perfume Spray 50 Ml Each",
        review: "",
        price: "₹2,199",
        deletePrice: "₹3,597",
        discount: "Save 39%",
    },
    {
        id: "51",
        image: "/NewArrival10.webp",
        hoverImage: "/NewArrival10.webp",
        description: "3 Pcs Perfume Set Shanaya, White Oudh And Oudh Al Hashmi Perfume Spray 50 Ml Each",
        review: "",
        price: "₹2,199",
        deletePrice: "₹3,597",
        discount: "Save 39%",
    },
    {
        id: "2",
        image: "/NewArrival11.webp",
        hoverImage: "/NewArrival11.webp",
        description: "The Story And White Oudh Perfume Spray 50 Ml Each",
        review: "",
        price: "₹1,399",
        deletePrice: "₹2,398",
        discount: "Save 42%",
    },
    {
        id: "53",
        image: "/NewArrival12.webp",
        hoverImage: "/NewArrival12.webp",
        description: "Shanaya And White Oudh Perfume Spray 50 Ml Each",
        review: "",
        price: "₹1,399",
        deletePrice: "₹2,398",
        discount: "Save 42%",
    },
    {
        id: "54",
        image: "/NewArrival13.webp",
        hoverImage: "/NewArrival13.webp",
        description: "Shanaya And Shanaya Gold Perfume Spray 50 Ml Each",
        review: "",
        price: "₹1,399",
        deletePrice: "₹2,398",
        discount: "Save 42%",
    },
    {
        id: "55",
        image: "/NewArrival14.webp",
        hoverImage: "/NewArrival14.webp",
        description: "Shanaya And Oudh Al Hashmi Perfume Spray 50Ml Each",
        review: "",
        price: "₹1,399",
        deletePrice: "₹2,398",
        discount: "Save 42%",
    },
    {
        id: "56",
        image: "/NewArrival15.webp",
        hoverImage: "/NewArrival15.webp",
        description: "Oudh Al Hashmi And White Oudh Perfume Spray 50Ml Each",
        review: "",
        price: "₹1,399",
        deletePrice: "₹2,398",
        discount: "Save 42%",
    },
    {
        id: "57",
        image: "/NewArrival16.webp",
        hoverImage: "/NewArrival16.webp",
        description: "The Story And Shanaya Perfume Spray 50 Ml Each",
        review: "",
        price: "₹1,399",
        deletePrice: "₹2,398",
        discount: "Save 42%",
    },
    {
        id: "58",
        image: "/NewArrival17.webp",
        hoverImage: "/NewArrival17.webp",
        description: "3 Pcs Attar Set Lazina, Safira And The Story Attar Perfume 5.5ML Each",
        review: "(2)",
        price: "₹799",
        deletePrice: "1,797",
        discount: "Save 56%",
    },
    {
        id: "59",
        image: "/NewArrival18.webp",
        hoverImage: "/NewArrival18.webp",
        description: "2 Pcs Attar Set Shanaya And Lazina 5.5 Ml Each",
        review: "",
        price: "₹699",
        deletePrice: "₹1,198",
        discount: "Save 42%",
    },
    {
        id: "60",
        image: "/NewArrival19.jpg",
        hoverImage: "/NewArrival20.jpg",
        description: "Zafar Royal Attar Perfume 10 ML",
        review: "",
        price: "₹1,999",
        deletePrice: "₹2,499",
        discount: "Save 20%",
    },
    {
        id: "61",
        image: "/NewArrival21.jpg",
        hoverImage: "/NewArrival22.jpg",
        description: "Sulook Royal Attar Perfume 10 ML",
        review: "",
        price: "₹1,999",
        deletePrice: "₹2,499",
        discount: "Save 20%",
    },
    {
        id: "62",
        image: "/NewArrival23.jpg",
        hoverImage: "/NewArrival24.jpg",
        description: "Tawakkul Royal Attar Perfume 10 ML",
        review: "",
        price: "₹1,999",
        deletePrice: "₹2,499",
        discount: "Save 20%",
    },
    {
        id: "63",
        image: "/NewArrival25.jpg",
        hoverImage: "/NewArrival26.jpg",
        description: "Zahra Royal Attar Perfume 10 ML",
        review: "",
        price: "₹1,999",
        deletePrice: "₹2,499",
        discount: "Save 20%",
    },
    {
        id: "64",
        image: "/NewArrival27.png",
        hoverImage: "/NewArrival28.png",
        description: "Lazina Luxury Attar Perfume",
        review: "(3)",
        price: "₹399",
        deletePrice: "₹599",
        discount: "Save 33%",
    },
    {
        id: "65",
        image: "/NewArrival29.webp",
        hoverImage: "/NewArrival29.webp",
        description: "3 Pcs Attar Set Shanaya, The Story And Safira 5.5 Ml Each",
        review: "(1)",
        price: "₹799",
        deletePrice: "₹1,797",
        discount: "Save 56%",
    }
];