export const BodySpray_DataArr = [
    {
        id: "33",
        image: "/BodySpray1.png",
        hoverImage: "/BodySpray1.png",
        description: "Afreen Alcohol Free Premium Deodorant Body Spray 200 ML pack of 2 Body spray",
        review: "(248)",
        price: "₹599",
        deletePrice: "₹798",
        discount: "Save 25%",
    },
    {
        id: "34",
        image: "/BodySpray2.jpg",
        hoverImage: "/BodySpray2.jpg",
        description: "Combo Afreen & Shanaya Alcohol Free Premium Deodorant Body spray 200 ML",
        review: "(1,378)",
        price: "₹699",
        deletePrice: "₹798",
        discount: "Save 12%",
    },
    {
        id: "35",
        image: "/BodySpray3.jpg",
        hoverImage: "/BodySpray3.jpg",
        description: "Shanaya Alcohol Free Premium Deodorant Body Spray",
        review: "(33)",
        price: "₹399",
        deletePrice: "₹599",
        discount: "Save 10%",
    },
    {
        id: "36",
        image: "/BodySpray4.png",
        hoverImage: "/BodySpray4.png",
        description: "Shanaya Alcohol Free Premium Deodorant Body spray 200 ML pack of 2 Body Spray",
        review: "(180)",
        price: "₹599",
        deletePrice: "₹798",
        discount: "Save 25%",
    },
];