export const IncenseStick_DataArr = [
    {
        id: "37",
        image: "/IncenseStick1.png",
        hoverImage: "/IncenseStick2.png",
        description: "Adilqadri Magical Moments Premium Quality Agarbatti ( Incense Stick ) 100 gms",
        review: "(9)",
        price: "₹499",
        deletePrice: "₹899",
        discount: "Save 44%",
    },
    {
        id: "38",
        image: "/IncenseStick3.png",
        hoverImage: "/IncenseStick4.png",
        description: "Lavender Premium Quality Agarbatti ( Incense Stick ) 100 gms",
        review: "(13)",
        price: "₹499",
        deletePrice: "₹899",
        discount: "Save 44%",
    },
    {
        id: "39",
        image: "/IncenseStick5.png",
        hoverImage: "/IncenseStick6.png",
        description: "Morning Blossom Premium Quality Agarbatti ( Incense Stick ) 100 gms",
        review: "(10)",
        price: "₹499",
        deletePrice: "₹899",
        discount: "Save 44%",
    },
    {
        id: "40",
        image: "/IncenseStick7.png",
        hoverImage: "/IncenseStick8.png",
        description: "Hasnain Premium Quality Agarbatti ( Incense Stick ) 100 gms",
        review: "(25)",
        price: "₹499",
        deletePrice: "₹899",
        discount: "Save 25%",
    },
    {
        id: "41",
        image: "/IncenseStick9.png",
        hoverImage: "/IncenseStick10.png",
        description: "Shanaya Gold Perfume Spray",
        review: "(11)",
        price: "₹1,199",
        deletePrice: "₹1,999",
        discount: "Save 40%",
    }
];