export const PerfumeSpray_DataArr = [
    {
        id: "22",
        image: "/PerfumeSpray1.jpg",
        hoverImage: "/PerfumeSpray2.jpg",
        description: "Luxury Gift Set 5 Pcs Premium Perfume Spray",
        review: "(39)",
        price: "₹1,599",
        deletePrice: "₹2,999",
        discount: "Save 47%",
    },
    {
        id: "23",
        image: "/PerfumeSpray3.png",
        hoverImage: "/PerfumeSpray3.png",
        description: "AQ 365 Perfume Spray",
        review: "(1,355)",
        price: "₹399",
        deletePrice: "₹999",
        discount: "Save 60%",
    },
    {
        id: "24",
        image: "/PerfumeSpray4.jpg",
        hoverImage: "/PerfumeSpray5.jpg",
        description: "Captivating Trio 3 Pcs Set of Premium Perfume Spray",
        review: "(1,027)",
        price: "₹999",
        deletePrice: "₹1,499",
        discount: "Save 33%",
    },
    {
        id: "25",
        image: "/PerfumeSpray6.jpg",
        hoverImage: "/PerfumeSpray7.jpg",
        description: "Elegance Trio 3 Pcs Premium Perfume Spray 30ml x 3",
        review: "(277)",
        price: "₹999",
        deletePrice: "₹1,999",
        discount: "Save 33%",
    },
    {
        id: "26",
        image: "/PerfumeSpray8.jpg",
        hoverImage: "/PerfumeSpray8.jpg",
        description: "Shanaya Gold Perfume Spray",
        review: "(11)",
        price: "₹1,199",
        deletePrice: "₹1,999",
        discount: "Save 40%",
    },
    {
        id: "27",
        image: "/PerfumeSpray9.jpg",
        hoverImage: "/PerfumeSpray9.jpg",
        description: "Oudh Al Hashmi Perfume Spray",
        review: "(145)",
        price: "₹449",
        deletePrice: "₹999",
        discount: "Save 55%",
    },
    {
        id: "28",
        image: "/PerfumeSpray10.jpg",
        hoverImage: "/PerfumeSpray11.jpg",
        description: "Royal Oudh Luxury Eau De Perfume Spray 100 ml",
        review: "(68)",
        price: "₹1,199",
        deletePrice: "₹3,299",
        discount: "Save 64%",
    },
    {
        id: "29",
        image: "/PerfumeSpray12.jpg",
        hoverImage: "/PerfumeSpray13.jpg",
        description: "Afreen Perfume Spray 50 ML",
        review: "(14)",
        price: "₹799",
        deletePrice: "₹1,299",
        discount: "Save 38%",
    },
    {
        id: "30",
        image: "/PerfumeSpray14.jpg",
        hoverImage: "/PerfumeSpray15.jpg",
        description: "Safwan Perfume Spray",
        review: "(2)",
        price: "799",
        deletePrice: "₹1,299",
        discount: "Save 38%",
    },
    {
        id: "31",
        image: "/PerfumeSpray16.jpg",
        hoverImage: "/PerfumeSpray17.jpg",
        description: "Glamour Oudh Perfume Spray 100 ML",
        review: "(12)",
        price: "₹2,499",
        deletePrice: "₹5,999",
        discount: "Save 58%",
    },
    {
        id: "32",
        image: "/PerfumeSpray18.jpg",
        hoverImage: "/PerfumeSpray19.jpg",
        description: "The Professor Perfume Spray 100 ML",
        review: "(21)",
        price: "₹1,999",
        deletePrice: "₹4,999",
        discount: "Save 60%",
    },
];